# Generated by Django 5.1.4 on 2025-01-08 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_remove_actividad_estado'),
        ('usuarios', '0002_perfil_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=False)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'actividad')},
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='actividades_resueltas',
            field=models.ManyToManyField(through='usuarios.UsuarioActividad', to='actividades.actividad'),
        ),
    ]
