# Generated by Django 5.1.4 on 2025-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nivel',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Medio', 'Medio'), ('Avanzado', 'Avanzado')], default='Básico', max_length=10),
        ),
    ]
