# Generated by Django 5.1.4 on 2025-01-04 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Básico', 'Básico'), ('Fácil', 'Fácil'), ('Medio', 'Medio'), ('Avanzado', 'Avanzado'), ('Experto', 'Experto')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('contenido', models.TextField()),
                ('nivel_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.nivel')),
            ],
        ),
    ]
