# Generated by Django 5.1.4 on 2025-01-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('opcion1', models.CharField(max_length=100)),
                ('opcion2', models.CharField(max_length=100)),
                ('opcion3', models.CharField(max_length=100)),
                ('respuesta_correcta', models.CharField(max_length=100)),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.nivel')),
            ],
        ),
    ]
