# Generated by Django 5.1.4 on 2025-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_solucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='Pregunta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividad',
            name='pista',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
