# Generated by Django 5.1.4 on 2025-01-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_actividad_pregunta_actividad_pista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='contenido',
        ),
    ]
