# Generated by Django 5.1.4 on 2025-01-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0010_alter_actividad_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='estado',
        ),
    ]
