# Generated by Django 5.1.4 on 2025-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0011_remove_actividad_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='nombre',
            field=models.CharField(choices=[('Básico', 'Básico'), ('Medio', 'Medio'), ('Avanzado', 'Avanzado')], max_length=20),
        ),
    ]
