# Generated by Django 5.1.4 on 2025-01-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0012_alter_nivel_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='terminal',
            field=models.BooleanField(default=False),
        ),
    ]
