# Generated by Django 5.1.4 on 2025-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0013_actividad_terminal'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
