# Generated by Django 5.1.4 on 2025-01-09 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historiaep',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/historia'),
        ),
        migrations.AddField(
            model_name='historiaep',
            name='priodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='informacion.periodohistoria'),
            preserve_default=False,
        ),
    ]
